name: Deployee StorageApp Backend
on: [push, workflow_dispatch]

jobs:
  Deployee:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: 44.219.36.207
      SSH_USER: ubuntu
      REMOTE_APP_DIR: /home/ubuntu/StorageApp_backend
      PM2_APP_NAME: myApp

    steps:
      - name: Checkout the  repoestry
        uses: actions/checkout@v4
      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: "26"
      - name: SETUP SSH
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"

          ssh-keyscan -H "$SSH_HOST" >> "$HOME/.ssh/known_hosts"

      - name: Deploye backend on EC2
        run: |
          ssh -i "$HOME/.ssh/id_rsa" "$SSH_USER@$SSH_HOST" << 'EOF'
          set -e

          cd /home/ubuntu/StorageApp_backend

          echo "🔥 Backend deployment started..."

          git fetch origin
          git reset --hard origin/main

          echo "✅ Code updated from GitHub"

          echo "Installing client dependencies  (npm ci)......"
          npm ci --no-audit --no-fund

          echo "✅ Dependencies installed"

          pm2 reload myApp

          echo "🔥 Backend deployed successfully"
          EOF
